ahoyapi: v2
usage: Streamsauce commands
env: .env
commands:
  docker:
    usage: Run docker-compose commands
    imports:
      - .ahoy/docker.ahoy.yml
  dbos:
    usage: Run dbos commands
    imports:
      - .ahoy/dbos.ahoy.yml
  setup:
    usage: Setup commands
    imports:
      - .ahoy/setup.ahoy.yml
  up:
    usage: Start services by profile
    imports:
      - .ahoy/up.ahoy.yml
  clean:
    usage: Remove all jpg, ts, and m3u8 files from output directories
    cmd: "find output -type f \\( -name '*.jpg' -o -name '*.ts' -o -name '*.m3u8' \\) -delete"
